print('please enter the following')
print('\n')
first_name = input('first name:')
Middle_name = input('middle name:')
last_name = input('last name:')
email_address = input('email address:')
phone_number = input('phone number:')
job_title = input('job tittle:')
id_number = input('id number:')
hair_colour = input('hair:')
eye_colour = input('eye:')
month = input('what month did you start?:')
have_you_recieved_advanced_training = input('have you recieved advanced training? yes/no:')

print('\n')
print('your id card is'.upper())
print('--------------------------------------------------------')
print(f'{last_name.upper()}, {first_name.capitalize()} {Middle_name.capitalize()}')
print(job_title.title())
print (f'Id: {id_number}')
print()
print(email_address.lower())
print(phone_number)
print()
print(f'Hair:  {hair_colour.capitalize()}                   Eye: {eye_colour.capitalize()}')
print(f'Month: {month.capitalize()}                    Training: {have_you_recieved_advanced_training.capitalize()}')
print('--------------------------------------------------------')
k = input('press enter to exit')