Color= input ('what is your Prefered colour?  ')
print('Your Prefered color is ' + Color+'!')
print()
Name= input ('What is your pet\'s name? ')
print('Your pet\'s name is ' + Name +'!')  
print()
Country= input ('What country do you currently live in? ')
print ('You currently reside in ' + Country)
print()
print ('Thanks for taking this short questionnaire')  
print()
k=input("Press enter to Exit")
