first_name = input ('please enter your first name:')
middle_name = input('please enter your middle name:')
Last_name = input('Please enter your last name:')
email_address = input('Please enter your email address:')
phone_number = input('please enter your phone number:')
job_tittle = input('please enter your job tittle:')
id_number = input('please enter your id number:')
print ()
print ('The ID card is')
print('----------------------------------------------------------------------------')
print (f'{Last_name.capitalize()}, {first_name.capitalize()} {middle_name.capitalize()}')
print (job_tittle.title())
print(f"ID: {id_number}")
print()
print (email_address.lower())
print(phone_number)     
print('----------------------------------------------------------------------------')
