# print ('Please enter the following')
# print ('\n')
# adjective = input ('adjective:')
# animal = input ('animal:')
# verb_A = input ('verb:')
# exclaimation = input ('exclaimation:')
# verb_B = input ('verb:')
# verb_C = input ('verb:') 
# plural_noun1 = input ('plural noun:')
# plural_noun2 = input ('plural noun:')
# fictional_creature = input ('fictional creature:')
# verb_D = input ('verb:')
# print ()
# print ('Your story Is')
# print ('\n')
# print ('The other day, I was really in trouble. It all started when I saw a very')
# print (f'{adjective.lower()} {animal.lower()} {verb_A} down the hallway. \"{exclaimation.capitalize()}!" I yelled. But all')
# print (f'I could think to do was to {verb_B} over and over. Miraculously,')
# print (f'that caused it to stop, but not before it tried to {verb_C}')
# print ('right in front of my family. It then asked if we would help him with its\' quest.')
# print (f'Without hesitation, We agreed to join the {animal} on this journey.')
# print (f'We set off immediately, facing many challenges along the way including treacherous {plural_noun1} and fierce {plural_noun2}.')
# print (f'But with the {animal}\'s magic and my family\'s determination, we were able to overcome each obstacle.')
# print (f'Finally, we reached the lair of a terrible {fictional_creature.capitalize()} and engaged in a fierce {verb_D}.')
# print (f'After a hard-fought battle, we emerged victorious, having saved the nearby village from the')
# print (f'terror of the {fictional_creature.capitalize()} and restoring peace to the land.')
# print (f'We returned home victorious and the {animal}, who was very grateful, decided to stay with us forever.')
# print()
# print('The End')
# print('\n')
# k= input ('press enter to exit')


print ('Please enter the following')
print ('\n')
adjective = input ('adjective:')
animal = input ('animal:')
verb_A = input ('verb:')
exclaimation = input ('exclaimation:')
verb_B = input ('verb:')
verb_C = input ('verb:') 
plural_noun1 = input ('plural noun:')
plural_noun2 = input ('plural noun:')
fictional_creature = input ('fictional creature:')
verb_D = input ('verb:')
print ()
print ('Your story Is')
print ('\n')
print ('The other day, I was really in trouble. It all started when I saw a very')
print (f'{adjective.lower()} {animal.lower()} {verb_A} down the hallway. \"{exclaimation.capitalize()}!" I yelled. But all')
print (f'I could think to do was to {verb_B} over and over. Miraculously,')
print (f'that caused it to stop, but not before it tried to {verb_C}')
# I added a few sentences to this line to make the story more interestiing
print ('right in front of my family. It then began barking obnoxiously.')
print (f'Without hesitation, my family and i ran outside in the direction of the parking lot to avoid being bitten by the {animal}.')
print (f'As we continued to look for as safe place to hide, we encountered many challenges along the way including treacherous {plural_noun1} and fierce {plural_noun2}.')
print (f'Luckily our {fictional_creature.capitalize()} friend arrived to save us, and we were able to overcome each obstacle.')
print (f'Finally, we traveled to the lair of the {adjective.lower()} {animal.lower()} and engaged in a fierce {verb_D}.')
print (f'After a hard-fought battle, we emerged victorious, reestablishing peace and safety to land.')
print (f'And we triumphantly made it home with our {fictional_creature.lower()} friend, and because of our sincere gratitude towards the {fictional_creature.lower()} it decided to stay with us forever.')
print()
print('The End')
print('\n')
k= input ('press enter to exit')

